### ISSUE TITLE
Printing PDF crashes instantly before timeout

### ISSUE THREAD

**Issue by xaviRodri** [bitcrowd/chromic_pdf#298] opened 2024-01-04 13:56 UTC
Hi there!

This has happened to me for a while, so I'm creating the issue to find & track the solution..

When printing a PDF (BUT NOT ALWAYS, just for some specific PDFs), I get this instant error, and then after the timeout I get the second one:

```
 13:47:55.105 [error] ChromicPDF received an 'Inspector.targetCrashed' message.

 This means an active Chrome tab has died and your current operation is going to time out.

 Known causes:

 1) External URLs in <link> tags in the header/footer templates cause Chrome to crash.
 2) Shared memory exhaustion can cause Chrome to crash. Depending on your environment, the
    available shared memory at /dev/shm may be too small for your use-case. This may
    especially affect you if you run ChromicPDF in a container, as, for instance, the
    Docker runtime provides only 64 MB to containers by default.

    Pass --disable-dev-shm-usage as a Chrome flag to use /tmp for this purpose instead
    (via the chrome_config option), or increase the amount of shared memory available to
    the container (see --shm-size for Docker).
```

```
** (ChromicPDF.Browser.ExecutionError) Timeout in Channel.run_protocol/3!

 The underlying GenServer.call/3 exited with a timeout. This happens when the browser was
 not able to complete the current operation (= PDF print job) within the configured
 15000 milliseconds.

 If you are printing large PDFs and expect long processing times, please consult the
 documentation for the `timeout` option of the session pool.

 If you are *not* printing large PDFs but your print jobs still time out, this is likely a
 bug in ChromicPDF. Please open an issue on the issue tracker.

 ---

 Current protocol:

 %ChromicPDF.Protocol{
   steps: [
     await: &ChromicPDF.Navigate.page_load_event/2,
     call: &ChromicPDF.PrintToPDF.print_to_pdf/2,
     await: &ChromicPDF.PrintToPDF.printed/2,
     call: &ChromicPDF.ResetTarget.reset_history/2,
     await: &ChromicPDF.ResetTarget.history_reset/2,
     call: &ChromicPDF.ResetTarget.blank/2,
     await: &ChromicPDF.ResetTarget.blanked/2,
     await: &ChromicPDF.ResetTarget.fsl_after_blank/2,
     output: &ChromicPDF.PrintToPDF.output/1
   ],
   state: %{
     :timeout => 15000,
     :name => "[FILTERED]",
     :output => "[FILTERED]",
     :size => 1,
     :__protocol__ => ChromicPDF.PrintToPDF,
     :checkout_timeout => "[FILTERED]",
     :html => "[FILTERED]",
     :capture_screenshot => %{},
     :print_to_pdf => %{
       "displayHeaderFooter" => true,
       "footerTemplate" => "[FILTERED]",
       "headerTemplate" => "[FILTERED]",
       "preferCSSPageSize" => true
     },
     :session_pool => [timeout: 15000],
     :max_uses => "[FILTERED]",
     :init_timeout => 5000,
     :close_timeout => "[FILTERED]",
     :offline => true,
     :ignore_certificate_errors => false,
     :unhandled_runtime_exceptions => :log,
     :last_call_id => 58976,
     :chrome_args => ["--disable-dev-shm-usage", "--no-sandbox"],
     :discard_stderr => false,
     :source_type => :html,
     :disable_scripts => true,
     :on_demand => false,
     "frameId" => "BD50B0FED77FA47ED74C0C9A95897A51",
     "sessionId" => "F23E67B74A4891AB54D14C7F3958E06D"
   }
 }

     (chromic_pdf 1.15.1) lib/chromic_pdf/pdf/browser/channel.ex:24: ChromicPDF.Browser.Channel.run_protocol/3
     (chromic_pdf 1.15.1) lib/chromic_pdf/pdf/browser/session_pool.ex:57: anonymous fn/3 in ChromicPDF.Browser.SessionPool.checkout!/3
     (nimble_pool 1.0.0) lib/nimble_pool.ex:349: NimblePool.checkout!/4
     (chromic_pdf 1.15.1) lib/chromic_pdf/pdf/browser/session_pool.ex:54: ChromicPDF.Browser.SessionPool.checkout!/3
     (chromic_pdf 1.15.1) lib/chromic_pdf/api.ex:72: anonymous fn/3 in ChromicPDF.API.chrome_export/4
     (chromic_pdf 1.15.1) lib/chromic_pdf/api/telemetry.ex:10: anonymous fn/2 in ChromicPDF.Telemetry.with_telemetry/3
     (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
     (chromic_pdf 1.15.1) lib/chromic_pdf/api.ex:27: anonymous fn/4 in ChromicPDF.API.print_to_pdf/3
```

As you can see, `--disable-dev-shm-usage` is already added and the timeout has been increased to 15s.
Also, I've checked and no external links exist either in headers or footers..

As I said, this only happens with certain PDFs, but I can't find what they have in common..
Anything I could do to fix or at least debug this?

I also get some warnings about the old interpreter 🤔 could be related to that?
```
**** Warning: You are using the legacy PDF interpreter (-dNEWPDF=false) which is now deprecated and unsupported
```

Thanks in advance!

**Comment by maltoe** [comment] 2024-01-04 21:38
Hi @xaviRodri,

The `Inspector.targetCrashed` notification tells you that Chrome's tab process has died, as you say instantly or at least before the window load event happens, as ChromicPDF was waiting for that notification.

Can you reproduce it locally? If so, try [`discard_errors: false`](https://hexdocs.pm/chromic_pdf/ChromicPDF.html#module-debugging-chrome-errors) to see if Chrome logs anything useful or compile with [`debug_protocols: true`](https://github.com/bitcrowd/chromic_pdf/blob/dc3f2a345a9d0f72a449f3dac9c9ab69cd0cf29b/config/config.exs#L6) to see the full glory of devtools protocol messages going back and forth. Or maybe enable JS logging, if you have a lot of JS.

Otherwise, I'm afraid this will be hard to debug. Do the same PDFs keep failing consistently?

> I also get some warnings about the old interpreter 🤔 could be related to that?

No, this is ghostscript and should disappear with https://github.com/bitcrowd/chromic_pdf/commit/6a45f521d4256c6c9056853493bf4e757efc1220 and Ghostscript >= 10.02.

**Comment by xaviRodri** [comment] 2024-01-08 16:19
Good news: I can reproduce locally.
More good news: after adding `discard_stder: false` & `debug_protocol: true` I get 1 more line of logs 😅

```
[0108/154119.851196:ERROR:nss_util.cc(55)] Failed to create /nonexistent/.pki/nssdb directory.
```

I hope this triggers something in your mind.. because I have no idea what this could be to be honest 😞 

Another note I can add: 
- This happened using gs 10.0.0 in Debian bookworm inside a docker container.
- Also tested with Alpine 3.18 and gs 10.02.0, same result

**Comment by maltoe** [comment] 2024-01-08 19:38
The error message looks like chrome is trying to create a file at `/nonexistent/.pki/nssdb` but failed. This could have a lot of reasons, I guess usual suspects in cases like this would be missing parent directories and incorrect permissions. "PKI" is public key infrastructure and nssdb is AFAIK Chromium's certificate store. Apart from that, this does not ring any bell unfortunately.

But great news that you can reproduce locally!

- Do the same PDFs keep failing consistently? In other words, are you confident that success/failure is correlated to the input HTML you provide?
- If so, I'd definitely next try to slim down your failing markup until it doesn't fail anymore
- If you can, share a minimal working example of the failing PDF (e.g. a Dockerfile and an `.exs` script would be great). Can't promise anything on my end, but if a MWE is available and the issue is simple to reproduce, maybe others would be interested in helping out as well.

Last but not least, to your note about gs versions:  The error you originally posted is 100% related to Chromium, not Ghostscript. Ghostscript is executed only when the PDF was successfully generated by Chromium. Hence, chromium version would be more interesting.

**Comment by xaviRodri** [comment] 2024-01-09 08:50
@maltoe I've just found the issue!

We had a link in the body of one of the sources (not in the header/footer). 
That link was inside an `img_tag`, so it was supposed to display an image.
Without this link, it just renders fine. 

Now.. should it be like this? Because I've tried both with `offline: true` and `offline: false` and it doesn't affect the result.
We should be able to have links there when `offline: false` right?
Or am I missing something?

**Comment by maltoe** [comment] 2024-01-09 19:22
@xaviRodri glad you found the issue

> That link was inside an img_tag, so it was supposed to display an image.

That wouldn't be valid HTML, would it? I suppose you mean `img` inside `a`?

> Now.. should it be like this?

"no" to "should it be like this", but that's about it what I can do for you. If this markup crashes Chrome, there's not much else you can do besides working around the issue (i.e. eliminating this link). Or perhaps try to reproduce it without ChromicPDF (e.g. with puppeteer, or simply by calling `chromium --print-to-pdf out.pdf my_bad_markup.html`, and see if you can pursue the issue further in the puppeteer / chromium bug trackers.

> We should be able to have links there when offline: false right?

Not sure. I don't think it should make a difference. `offline: true` basically tells Chrome to emulate missing network access, so if anything, it may stop Chrome from prefetching the link. But rendering it should work fine with or without, IMO.

**Comment by maltoe** [comment] 2024-01-09 19:23
Also, again, it would be superb if you could produce a minimal working example. I'd be keen to reproduce it myself and perhaps document it.

**Comment by xaviRodri** [comment] 2024-01-10 15:05
@maltoe I'm working on a mini repo so you can try it too 👍 

> That wouldn't be valid HTML, would it? I suppose you mean img inside a?

Nono, I mean a link inside the src of the image tag.

**Comment by xaviRodri** [comment] 2024-01-11 08:30
Hi again!
@maltoe here you have the repo: https://github.com/xaviRodri/chromic_example

You just need docker and follow the README 👍

**Comment by xaviRodri** [comment] 2024-01-11 10:16
FYI: 
I thought the problem would be the link to the image itself, but I'm still getting the error even if I use data URI as the source of the image..
Again, this doesn't happen in my local (MacOS with M1) but in the docker image (Debian)

**Comment by maltoe** [comment] 2024-01-11 10:25
@xaviRodri thx for the repo

* Had to disable seccomp first (`docker run --security-opt seccomp=unconfined ...`) to allow sandboxing inside docker
* PDF creation worked fine inside docker
* Also tried to create the PDF outside docker, just using the HTML markup, no issue

However, my machine has an x86 CPU and runs Linux on the host as well, so maybe this is a hint that the issue is related to the arm64 builds of Chromium? I'll try to get someone with Apple silicon to confirm this.

**Comment by xaviRodri** [comment] 2024-01-11 10:43
@maltoe I know why it worked for you.
The problem it's in the image itself (well actually its link). This one you have in the repo is one I got from imgur to not post the one I was using when testing. Using the imgur image worked for me too now..

Could you please try to update the src with what you will find inside the following link?
https://www.protectedtext.com/maltoe01.2024
password: maltoe2024

**Comment by maltoe** [comment] 2024-01-11 11:47
Can confirm, reproduced the issue with the cloudinary link inside the bookworm docker image. Same link outside that image on my ubuntu host works fine. Recap my tests

- :green_circle: the lama from imgur in all scenarios
- :green_circle: your cloudinary URL on my Ubuntu host
- :green_circle: your cloudinary image (served via local httpd) on my Ubuntu host
- :green_circle: your cloudinary image (served via local httpd) on my Ubuntu host
- :red_circle: your cloudinary URL inside the bookworm container
- :green_circle: other cloudinary URLs inside the bookworm container
- :green_circle: your cloudinary image (served via file:// with `chromium --print-to-pdf`, see below) inside the bookworm container

So currently we think it's a weird combination of the bookworm container, this particular image and only when serving from cloudinary (or possibly served via HTTP in general, didn't try local httpd in the container)? Pretty odd issue :/

--- 

However, I did manage to reduce your example and take ChromicPDF out of the equation

```html
<html>
<body>
  <img src="... your cloudinary URL ...">
</body>
</html>
```

```sh
chromium --headless --print-to-pdf test.html
```

^^ This hangs indefinitely, too, only inside the bookworm container. So - I guess this is not a new conclusion - I'm relatively confident to say this is not an issue within ChromicPDF. With that, I unfortunately need to reduce my efforts on this issue a little bit. Perhaps opening an issue in the Chromium bug tracker would make sense now?

**Comment by maltoe** [comment] 2024-01-17 11:14
@xaviRodri I'll close this for now, as I don't see a way of fixing this within ChromicPDF. If you find out a workaround that fixes it which could be incorporated into Chromic, feel free to reopen. Best of luck to you!

**Closed by maltoe** 2024-01-17 11:14 UTC

**Comment by mpraski** [comment] 2024-10-22 14:08
@xaviRodri I know this is an old issue, but I've recently run int the same problem with trying to write to `nonexistent`. In case my dockerized setup chrome was trying to create/write directories it had no permission to write to, and setting the XDG home/cache directories to something writable solved the issue:

```
FROM debian:bookworm-20240926-slim

ENV XDG_CONFIG_HOME=/tmp/.chromium
ENV XDG_CACHE_HOME=/tmp/.chromium

RUN apt-get update -y && \
    apt-get install -y libstdc++6 openssl libncurses5 locales ca-certificates curl gnupg \
    && curl --location --silent https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update -y \
    && apt-get install google-chrome-stable -y --no-install-recommends \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

...
    
```
