### ISSUE TITLE
`wait_for` option not working

### ISSUE THREAD

**Issue by dgigafox** [bitcrowd/chromic_pdf#104] opened 2021-02-22 11:15 UTC
Hello! First of all, thanks for the awesome work!

I am unable to display font-awesome icons in the exported pdf. In a normal website lifecycle, the font-awesome icon will display after some time. That is why I thought the `wait_for` option will be of great use. But it seems it always times out and can't find whatever selector and attr I set. This is how I set it up:

Version: 0.7.1

`config.exs`
```elixir
config :my_app, ChromicPDF, on_demand: false, session_pool: [timeout: 60_000], offline: false
```

`my_pdf_template.html.eex`
```eex
<head>
  <link rel="stylesheet" href="<%= Routes.static_url(@conn, "/css/tailwind.css") %>">
</head>

<body class="bg-white">
  <div id="print-ready"></div>
  <i class="far fa-envelope"></i>
  ... more contents ...

  <script defer src="<%= Routes.static_url(@conn, "/js/app.js") %>" ></script>
</body>
```

`app.js`
```javascript
import { faEnvelope } from "@fortawesome/pro-regular-svg-icons";
import { dom, library } from "@fortawesome/fontawesome-svg-core";

function handleDOMContentLoaded() {
  library.add(faEnvelope);
  dom.watch();
  $("#print-ready").attr("ready-to-print", "");
}

window.addEventListener("DOMContentLoaded", handleDOMContentLoaded, false);
```

Then I just call an endpoint that will execute the download of the pdf via a controller:
`pdf_controller.ex`
```elixir
def export(conn, params) do
... some code to build assigns ...
template = Phoenix.HTML.safe_to_string(PdfView.render("my_pdf_template.html", assigns))

[content: template]
|> ChromicPDF.Template.source_and_options()
|> ChromicPDF.print_to_pdf(
    wait_for: %{selector: "#print-ready", attribute: "ready-to-print"},
    output: fn path ->
      conn
      |> put_resp_content_type("application/pdf")
      |> send_download({:file, path}, filename: "export.pdf")
      |> halt()
    end
  )

end
```

Even I add an inline script in the template that adds the attribute `ready-to-print` it seems it still cannot find the element and eventually times out.

Without `wait_for` the pdf can be downloaded successfully, although the font-awesome icons are not visible.

**Comment by maltoe** [comment] 2021-02-22 13:30
Hey @dgigafox 

to analyze this properly we'll have to look into what messages Chrome actually sends you, notably whether you receive the `DOM.attributeModified` message (if it times out, it seem's you don't). This can be done, for instance, by inserting a `IO.inspect(msg)` [here](https://github.com/bitcrowd/chromic_pdf/blob/066da34f8fb24e04a3ad201d5023cd5d515b4b67/lib/chromic_pdf/pdf/browser/channel.ex#L67). 

A few questions beforehand though about your code:

1. Setting the options in the `config/....exs` files like you do has no effect if you don't also load them in your `Application` module, i.e. where you start ChromicPDF in your supervisor. ChromicPDF will not load them from the application environment. Though I don't suspect any of the options you've shown to be a reason for it failing.
2. You seem to be using jQuery, but I don't see it being loaded in `app.js` -> did you just omit this part?
3. According to its docs, jQuery's [attr](https://api.jquery.com/attr/) function with a value of `""` should still set the attribute, right? You could try using [`setAttribute`](https://developer.mozilla.org/de/docs/Web/API/Element/setAttribute) instead.
4. (this is my most likely guess) You're waiting for the `DOMContentLoaded` event in your js code, yet I'm not sure if this is actually emitted when you're setting the DOM content with `setDocumentContent` (that is what happens when you use the `{:html, "foo"}` option of ChromicPDF) -> could you try printing this from a URL and see whether it works then? (i.e. bypass `Template.source_and_options()` and instead use `ChromicPDF.print_to_pdf({:url, ...}, ...`)

hope this helps
malte

**Comment by dgigafox** [comment] 2021-02-22 14:46
@maltoe Thanks for the response!

1. Yup it was just omitted, but I load it in the supervisor like so:
`application.ex`
```elixir
defmodule MyApp.Application do
  @chromic_pdf_opts Application.compile_env!(:my_app, ChromicPDF)
  def start(_, _) do
     children = [{ChromicPDF, @chromic_pdf_opts}]
     opts = [strategy: :one_for_one, name: MyApp.Supervisor]
     Supervisor.start_link(children, opts)
  end
end
```

2. Yup just omitted too. But as per your number 3 suggestion. I did change it to:
```javascript
const printElement = document.getElementById("print-ready");
printElement.setAttribute("ready-to-print", "")
```

3. Same applies with number 2
4. Do you mean creating a new API where I can just render the html and put that API as url? I actually did try that a while ago, but no luck. There is an error saying something like `No key noSelectorId`. I hope I did log that one but might try it again to catch the exact error and put it here in the comments.

By the way, I did not see any `DOM.attributeModified` message here are the messages I have logged:
[CHROMIC_CHANNEL_MSG_LOG.txt](https://github.com/bitcrowd/chromic_pdf/files/6022696/CHROMIC_CHANNEL_MSG_LOG.txt)

The most notable thing that I have seen is that I can confirm the elements I defined are present:
```elixir
%{
  "method" => "DOM.setChildNodes",
  "params" => %{
    "nodes" => [
      %{
        "attributes" => ["id", "print-ready"],
        "backendNodeId" => 68,
        "childNodeCount" => 0,
        "localName" => "div",
        "nodeId" => 5,
        "nodeName" => "DIV",
        "nodeType" => 1,
        "nodeValue" => "",
        "parentId" => 4
      },
      %{
        "attributes" => ["class",
         "p-10 grid grid-flow-row grid-cols-2 items-start gap-4", "id",
         "pdf-content"],
        "backendNodeId" => 64,
        "childNodeCount" => 8,
        "localName" => "div",
        "nodeId" => 6,
        "nodeName" => "DIV",
        "nodeType" => 1,
        "nodeValue" => "",
        "parentId" => 4
      }
    ],
    "parentId" => 4
  },
  "sessionId" => "F6A8AE6B17DB72DAC0A7903FB9E0D596"
}
```

**Comment by maltoe** [comment] 2021-02-22 15:11
🤔  hmm, this looks all good, yes. Not sure what's happening. The `DOM.setChildNodes` message is new to me, but it indeed looks like Chrome tells you your elements are existing. The lack of the `DOM.attributeModified` message still makes me think your JS code is for some reason not executed... Could you try to just set the attribute in an embedded script in your HTML (like it's done [in the docs](https://hexdocs.pm/chromic_pdf/ChromicPDF.html#print_to_pdf/2-wait-for-dynamic-content)):

```html
<script>
  function makeItWork() {
    const element = document.getElementById('print-ready');
    element.setAttribute('ready-to-print', '');
  }


  makeItWork();
</script>
```

TBH I have no idea yet, and also haven't personally used this feature yet, so it might as well be broken :)... We need to keep eliminating "working" parts of your code to circle in on the actual offending part.

**Comment by maltoe** [comment] 2021-02-22 15:16
Also, what does `Routes.static_url(@conn, "/js/app.js")` return? Is this a relative path? If so, Chrome won't know where to load it from, it has to be an absolute URL. Maybe inspecting the rendered template can also help us.

**Comment by maltoe** [comment] 2021-02-22 15:23
Nevermind my last message, it returns the URL.

**Comment by dgigafox** [comment] 2021-02-22 15:46
@maltoe So I did your suggestion:
```elixir
<script>
  function makeItWork() {
    const element = document.getElementById('print-ready');
    element.setAttribute('ready-to-print', '');
  }
  makeItWork();
</script>
```

It did not work at first, but when I try to adjust the timeout it worked. `setTimeout(() => makeItWork, 5000)`
But transferring this script to `app.js` separating it from `DOMContentLoaded`event and just running it directly, seems to not work. Does this mean it does not read imported script from files? 🤔

**Comment by maltoe** [comment] 2021-02-22 16:50
> Does this mean it does not read imported script from files?

If your `static_url` returns a routable URL (e.g. `http://localhost:4000/some/path`), I wouldn't know why it would not.

@jarimatti as you implemented this feature, any idea?

**Comment by jarimatti** [comment] 2021-02-22 17:31
This is strange, no immediate ideas. As soon as ChromicPDF has registered interest to the `print-ready` element (calls to `DOM.getDocument` and `DOM.querySelector`) it should get the attribute change event `DOM.attributeModified` and move on.

The only case I can think of if the attribute is already set, before we call `DOM.querySelector`. That would cause it to misbehave.

I will take a look at the event logs later today.

**Comment by dgigafox** [comment] 2021-02-22 17:46
Thanks @jarimatti and @maltoe. When I get the free time, I will create a small application that we can test and inspect.

**Comment by jarimatti** [comment] 2021-02-22 17:51
I suspect (handwaving here) the `{:html, ...}` may cause some issues within Chrome, so testing with `{:url, ...}` would be interesting.

In addition you can enable the Chrome debug log in ChromicPDF configuration. That could also reveal something. See the docs for `discard_stderr` option: https://hexdocs.pm/chromic_pdf/ChromicPDF.html#module-debugging-chrome-errors

**Comment by dgigafox** [comment] 2021-02-23 04:41
@jarimatti @maltoe Thanks for the response and suggestion.
So I tried it again in url. I created 2 endpoints, one for sending the download and one for displaying the view to be exported.
This time `app.js` can be read.

`app.js`
```js
function loadDynamicContent() {
  const element = document.getElementById('print-ready');

  if (element) {
    element.innerText = "Dynamic javascript content from app.js on load event";
    element.setAttribute('ready-to-print', '');
  }
}

loadDynamicContent();
```
I can say that it worked because when I visit the url (view endpoint) and in the pdf itself the text `Dynamic javascript content from app.js on load event` is there.

But now, when I try to add `wait_for` in the opts,
```elixir
wait_for = %{selector: "#print-ready", attribute: "ready-to-print"}
ChromicPDF.print_to_pdf({:url, "http://localhost:4000/export/view"}, wait_for: wait_for)
```

it gives me an error
`exited in: GenServer.call(#PID<0.18373.0>, {:run_protocol, %ChromicPDF.Protocol{result_fun: nil, state: %{:capture_screenshot => %{}, :html => "", :output => #Function<2.110873207/1 in MyAppWeb.ControllerHelpers.download_pdf_via_url/4>, :print_to_pdf => %{"footerTemplate" => "", "headerTemplate" => ""}, :set_cookie => %{domain: "localhost", name: "_myapp_key", value: “<cookie_here>“}, :source_type => :url, :url => "http://localhost:4005/app/profile/75b484bc-503f-4e57-92e4-2e6c4bf3ab70/notes/export/view", :wait_for => %{attribute: "ready-to-print", selector: "#print-ready"}, "sessionId" => "2DF1B5E33CA877CABD480AEB808DEFAA"}, steps: [call: &ChromicPDF.PrintToPDF.set_cookie/2, await: &ChromicPDF.PrintToPDF.cookie_set/2, call: &ChromicPDF.PrintToPDF.navigate/2, await: &ChromicPDF.PrintToPDF.navigated/2, await: &ChromicPDF.PrintToPDF.frame_stopped_loading/2, call: &ChromicPDF.PrintToPDF.get_document/2, await: &ChromicPDF.PrintToPDF.get_document_response/2, call: &ChromicPDF.PrintToPDF.query_selector/2, await: &ChromicPDF.PrintToPDF.query_selector_response/2, await: &ChromicPDF.PrintToPDF.attribute_modified/2, call: &ChromicPDF.PrintToPDF.print_to_pdf/2, await: &ChromicPDF.PrintToPDF.printed/2, call: &ChromicPDF.PrintToPDF.reset_history/2, await: &ChromicPDF.PrintToPDF.history_reset/2, call: &ChromicPDF.PrintToPDF.clear_cookies/2, await: &ChromicPDF.PrintToPDF.cleared/2, call: &ChromicPDF.PrintToPDF.blank/2, await: &ChromicPDF.PrintToPDF.blanked/2, await: &ChromicPDF.PrintToPDF.fsl_after_blank/2, output: &ChromicPDF.PrintToPDF.output/1]}}, 60000) ** (EXIT) an exception was raised: ** (KeyError) key "selectorNodeId" not found in: %{:capture_screenshot => %{}, :html => "", :last_call_id => 16, :output => #Function<2.110873207/1 in MyAppWeb.ControllerHelpers.download_pdf_via_url/4>, :print_to_pdf => %{"footerTemplate" => "", "headerTemplate" => ""}, :set_cookie => %{domain: "localhost", name: "_myapp_key", value: “<cookie_here>”}, :source_type => :url, :url => "http://localhost:4005/app/profile/75b484bc-503f-4e57-92e4-2e6c4bf3ab70/notes/export/view", :wait_for => %{attribute: "ready-to-print", selector: "#print-ready"}, "frameId" => "B20C27CD30B65151FD5CCAA798139F42", "rootNodeId" => 1, "sessionId" => "2DF1B5E33CA877CABD480AEB808DEFAA"} (chromic_pdf 0.7.1) lib/chromic_pdf/pdf/protocol_macros.ex:231: ChromicPDF.ProtocolMacros.get_in_state!/2 (chromic_pdf 0.7.1) lib/chromic_pdf/pdf/protocol_macros.ex:209: ChromicPDF.ProtocolMacros.notification_matches?/3 (elixir 1.11.3) lib/enum.ex:3333: Enum.all_list/2 (chromic_pdf 0.7.1) lib/chromic_pdf/pdf/protocols/print_to_pdf.ex:51: ChromicPDF.PrintToPDF.attribute_modified/2 (chromic_pdf 0.7.1) lib/chromic_pdf/pdf/protocol.ex:111: ChromicPDF.Protocol.do_test/4 (chromic_pdf 0.7.1) lib/chromic_pdf/pdf/protocol.ex:102: ChromicPDF.Protocol.test/2 (chromic_pdf 0.7.1) lib/chromic_pdf/pdf/protocol.ex:95: ChromicPDF.Protocol.run/3 (elixir 1.11.3) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2 (chromic_pdf 0.7.1) lib/chromic_pdf/pdf/browser/channel.ex:68: ChromicPDF.Browser.Channel.handle_info/2 (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4 (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6 (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
`

**Comment by jarimatti** [comment] 2021-02-23 08:27
I'm not able to reproduce this with freshly downloaded Chrome 88.0.4324.192, Chromic PDF 0.7.1 and Elixir 1.11.3, running on Mac OS X 11.2.

The missing `selectorNodeId` sounds odd: it is as if the response to `DOM.queryElementById` didn't give any results or that something went wrong there. The relevant code is around here:
https://github.com/bitcrowd/chromic_pdf/blob/066da34f8fb24e04a3ad201d5023cd5d515b4b67/lib/chromic_pdf/pdf/protocols/print_to_pdf.ex#L38-L60

The `DOM.querySelector` response `nodeId` is set to the `selectorNodeId` in the state in the stack trace. @maltoe , is it possible that some other response or notification ends up between the `call` to `DOM.queryelementById` and the `await_response`? I recall they should be correlated but I could be wrong.

My simple test JS, served via Phoenix (note the `setTimeout`, you will see timeout error if the attribute is there before Chromic has a chance to query the element).

`index.html.eex`:
```
<div class="document">
  <div id="print-ready"></div>

  <h1>Hello World!</h1>
  <h1 id="js-hello">
</div>

<script src="js/test.js"></script>
<script>
  setTimeout(() => loadDynamicContent(), 500);
</script>
```

`js/test.js`:
```
function loadDynamicContent() {
    // Call any JS libraries/frameworks to set the dynamic content.
    const dynamic_element = document.getElementById('js-hello');
    dynamic_element.innerText = "Dynamic content from Javascript";

    // When ready, set the attribute:
    const element = document.getElementById('print-ready');
    element.setAttribute('ready-to-print', '');
}
```

Function to print:
```
  def print do
    ChromicPDF.print_to_pdf(
      {:url, "http://localhost:4000/"},
      output: "test.pdf",
      wait_for: %{
        selector: "#print-ready",
        attribute: "ready-to-print"
      }
    )
  end
```

**Comment by jarimatti** [comment] 2021-02-23 08:42
@dgigafox , one difference I see is that in my (very simple) example I have different element for the content and `print-ready` ID. As a workaround could you try that in your end: a dummy element with ID `print-ready` that only gets the attribute, no other changes?

**Comment by maltoe** [comment] 2021-02-23 08:47
@jarimatti 

> The DOM.querySelector response nodeId is set to the selectorNodeId in the state in the stack trace. @maltoe , is it possible that some other response or notification ends up between the call to DOM.queryelementById and the await_response? I recall they should be correlated but I could be wrong.

No, don't think this is possible. I think what happened is that the `DOM.querySelector` response arrived but didn't contain a `nodeId`  param. Which I think is a bug, the `await_response` call should error out if the message arrives but the payload doesn't conform to our "spec" (see #106). However, we need to find out _why_ the `nodeId` wasn't there.

**Comment by jarimatti** [comment] 2021-02-23 09:09
> However, we need to find out _why_ the `nodeId` wasn't there.

Agreed. The [DevTools protocol docs](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-querySelector) only mention the `nodeId`, no mention of it being missing.

Would be nice if we could log the DevTools protocol messages for diagnostics via some means, e.g. config flag or some other setting: the messages should shed some light into this. Not sure if Chrome can do that natively?

**Comment by maltoe** [comment] 2021-02-26 15:10
@dgigafox any news?

**Comment by dgigafox** [comment] 2021-02-27 01:53
@maltoe @jarimatti sorry for the late reply guys. For the meantime, I resorted back to using fontawesome cdn and passing html to print_to_pdf and removing the wait_for opt. It's working but some of the icons are missing especially the custom ones. I also noticed that when I used {:url,...} some css are not working as well like the custom background colors (I am using tailwind).

Will have to try @jarimatti's suggestion (the simplified approach) and see if there's any difference.

**Comment by maltoe** [comment] 2021-03-15 15:41
@dgigafox Did you have a chance to further investigate this?

If it is still an issue: I reworked the `wait_for` option quite a bit on current `main`, maybe you could give it another try. Also, I added the `evaluate` option that allows to run arbitrary JS scripts before printing, so alternatively you could try to run your `handleDOMContentLoaded` function from this script. Would be interested to hear about any issues you encounter.

I'll close this issue for now as we're not working on it anymore and there was some silence in between, feel free to re-open.

**Closed by maltoe** 2021-03-15 15:41 UTC
